### ISSUE TITLE
Failed to publish API.

### ISSUE THREAD

**Issue by kolychev1995** [apiman/apiman-docker#20] opened 2018-07-13 13:38 UTC
I use the docker (Docker version 17.03.0-ce, build 60ccb22) APIMan on wildfly 10 1.3.5.Final and Vert.x Gateway 1.3.5.Final Vert.x 3.4.2. I installed vertx gateway into wildfy api manager, but when I am trying to publish api I'm getting error:

```
io.apiman.manager.api.rest.contract.exceptions.ActionException: Failed to publish API.
	at io.apiman.manager.api.rest.impl.util.ExceptionFactory.actionException(ExceptionFactory.java:331)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.publishApi(ActionResourceImpl.java:230)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.performAction(ActionResourceImpl.java:105)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl$Proxy$_$$_WeldClientProxy.performAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.Exception: Api publishing failed: 500
	at io.apiman.manager.api.gateway.rest.GatewayClient.publish(GatewayClient.java:225)
	at io.apiman.manager.api.gateway.rest.RestGatewayLink.publishApi(RestGatewayLink.java:167)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.publishApi(ActionResourceImpl.java:204)
	... 79 more
Caused by: java.lang.Exception: Api publishing failed: 500
	at io.apiman.manager.api.gateway.rest.GatewayClient.publish(GatewayClient.java:220)
	... 81 more
```

**Comment by michelkaeser** [comment] 2019-01-08 15:33
Same with `docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly11:1.5.1.Final`

**Comment by jesseerdmann** [comment] 2020-10-21 20:30
I am getting this with the current version of apiman/on-wildfly with version 2.0.0 of APIman and 20 of Wildfly.  Any suggestions on what might be causing this and how to fix it?

**Comment by EricWittmann** [comment] 2020-10-21 20:40
I just tried the docker image and was able to confirm that the Gateway link is not being properly configured for some reason.  Basically I just ran the docker image and then navigated here (as an admin user):

http://localhost:8080/apimanui/api-manager/admin/gateways/TheGateway

On that page you can click **Test Gateway** to see if the config is correct.  It failed for me:

![image](https://user-images.githubusercontent.com/1890703/96784764-e2370200-13bb-11eb-88b1-052e965e893d.png)

What I did to fix it was change the endpoint credentials password to `apimanager123!` (which is the default password for that user).  Somewhere that default password is no longer being properly configured.  I'll need to dig into it further unless one of the other @apiman/maintainers has an idea offhand.

**Comment by volkflo** [comment] 2020-10-22 05:16
@EricWittmann I will look into this today. I am pretty sure I know where to look up this.

**Comment by volkflo** [comment] 2020-10-22 06:52
@EricWittmann There is something broken in the configs. The default password is `apiman123!` (this was not changed since 2015 in the keycloak realm.)

https://github.com/apiman/apiman/blame/fbd0fe23c705b27595a5b8530f03ad790df927d8/distro/data/src/main/resources/data/apiman-realm-for-keycloak.json#L39-L47

And the gatway is also correct configured:
https://github.com/apiman/apiman/blame/fbd0fe23c705b27595a5b8530f03ad790df927d8/distro/data/src/main/resources/bootstrap/default-gateway.json#L16

Everything works in the current master branch of apiman.

But with the developer portal PR I recreated the bundled keycloak H2 db from the realm and did not reuse the one you created before.
It is possible that there was a wrong password in the old keycloak db.

So this means that everything should be fixed in apiman 2.1.0. I pushed also a PR that forces a password refresh in the configs (https://github.com/apiman/apiman/pull/922)

**Comment by volkflo** [comment] 2020-10-22 06:55
@jesseerdmann For you, the simplest workaround is to change the password to the one Eric mentioned or define your own one in keycloak (which is pretty recommended).

**Comment by EricWittmann** [comment] 2020-10-22 13:37
Sorry @volkflo I didn't see this thread prior to commenting on your PR.  If we're confident that the quickstart works on `master` then that's fine.  I didn't realize there is a new keycloak DB.

**Comment by volkflo** [comment] 2020-10-22 13:43
@EricWittmann no problem :) It would be great if you could confirm that this works on master branch, too :)

**Comment by EricWittmann** [comment] 2020-10-22 15:21
I've confirmed that `master` looks good with respect to the Gateway credentials config.  I also really like the update to the sidebar look and feel - looks much nicer now.

One thing that was slightly annoying was that localhost:8080 is no longer a valid redirect URI.  I'm guessing that's deliberate (it's obviously much more secure).  However, I figured I would mention it:  thoughts on maybe adding http:8080 back in to the default config of the "apimanui" keycloak client?

**Comment by EricWittmann** [comment] 2020-10-22 15:21
In any case, I'm closing this because it is working on `master` and will be fixed in the next release.

**Closed by EricWittmann** 2020-10-22 15:21 UTC

**Comment by volkflo** [comment] 2020-10-22 15:33
No, I do not have a problem if you add port 8080 again :)Freundliche GrüßeFlorian VolkAm 22.10.20, 17:21 schrieb Eric Wittmann <notifications@github.com>:

   
  I've confirmed that master looks good with respect to the Gateway credentials config. I also really like the update to the sidebar look and feel - looks much nicer now. 
  One thing that was slightly annoying was that localhost:8080 is no longer a valid redirect URI. I'm guessing that's deliberate (it's obviously much more secure). However, I figured I would mention it: thoughts on maybe adding http:8080 back in to the default config of the "apimanui" keycloak client?

**Comment by jesseerdmann** [comment] 2020-10-22 19:01
At the moment I am just trying to test out the functionality including pulling the image into our existing Docker compose document to support some new APIs we are adding, so I hadn't changed the passwords, yet.   

However, I'm still struggling a bit here.  I went ahead and changed the passwords in Keycloak for the admin and apimanager users as well as the Keycloak admin user.  However, I am still having the same issue when I log into apimanui using the updated credentials.  I have tried to update the gateway connection information, but keep getting "Unauthorized" in response to the connection test using the original apimanager password, the one I updated it to in Keycloak, as well as the one mentioned by Eric above.  I've even logged in to the container and am trying to curl using various sets of credentials and I haven't found one that works yet.

**Comment by volkflo** [comment] 2020-10-23 05:20
@jesseerdmann Please try to create a new user for the gateway and assign the role `apipublisher`. 
Then remove the part before the username in config like so:
![image](https://user-images.githubusercontent.com/13332383/96959291-f7b54480-14ff-11eb-8163-a3ccc7e60412.png)

**Comment by jesseerdmann** [comment] 2020-10-23 14:35
Same result.  I have my system running on port 4443 for reference, but this is what I get from curl on the system (obviously won't be using this password anywhere that is reachable by the internet):

```
[jboss@api ~]$ curl -k -U gems_apimanager:gems_admin https://localhost:4443/apiman-gateway-api
<html><head><title>Error</title></head><body>Unauthorized</body></html>
```

**Comment by EricWittmann** [comment] 2020-10-26 14:01
Please keep us updated on your progress.  I have no theory that could explain what you're seeing!  I'd be very interested to know what is going on.... :)

**Comment by Pabubung** [comment] 2021-03-27 07:43
![image](https://user-images.githubusercontent.com/38039071/112713884-19c94d80-8f0a-11eb-85eb-4531f1045e63.png)

and in console: 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Hello friends, I got this error when I try to publish my first API. Any solution to solve this problem? Thank you

**Comment by Pabubung** [comment] 2021-03-27 07:45
I run apiman 2.0.0 final overlay for wildfly 20.0.1 . Thank you

**Comment by msavy** [comment] 2021-03-27 07:46
Look in the network tab of your developer console and see what the details
of the failed network request is when you attempt to publish.


> [image: image]
> <https://user-images.githubusercontent.com/38039071/112713884-19c94d80-8f0a-11eb-85eb-4531f1045e63.png>
>

**Comment by Pabubung** [comment] 2021-03-27 08:05
> Look in the network tab of your developer console and see what the details of the failed network request is when you attempt to publish.
> […](#)
> [image: image] <https://user-images.githubusercontent.com/38039071/112713884-19c94d80-8f0a-11eb-85eb-4531f1045e63.png>

This is details I got on terminal: 

WARN  [org.keycloak.events] (default task-15) type=LOGIN_ERROR, realmId=Apiman, clientId=apiman-gateway-api, userId=0f238557-35a5-4767-9a75-aa06988f82e9, ipAddress=127.0.0.1, error=invalid_user_credentials, auth_method=openid-connect, grant_type=password, client_auth_method=client-secret, username=apimanager, authSessionParentId=ce5b7240-dfba-4920-ab9f-b21078dddf32, authSessionTabId=Yq-pZRY_kMk

And this is on network developer console:

![image](https://user-images.githubusercontent.com/38039071/112714629-c1944a80-8f0d-11eb-85cd-849622d7a4b1.png)

![image](https://user-images.githubusercontent.com/38039071/112714655-ce18a300-8f0d-11eb-9aad-2930dfcbc46c.png)

**Comment by volkflo** [comment] 2021-03-29 06:55
This seems that some of the credentials may be wrong.
Can you go to Gateways -> The Gateway -> and press the "Test" button as described [here](https://apiman.gitbooks.io/apiman-production-guide/content/production-guide/manager/manager.html#_point_the_api_manager_to_the_api_gateway):
![image](https://user-images.githubusercontent.com/13332383/112797812-3da4a480-906c-11eb-93b6-bde87d7faf6e.png)

Then please post the results, also the wildfly log would be helpful for us :)

**Comment by righettod** [comment] 2021-04-05 08:10
Hi,

I have just run the docker command from the course (no creds changed):

```shell
$ docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly:2.0.0.Final
```

All seems OK (I can create org, api, plan, etc) but I cannot publish an API so I have performed the test above and it failed:

![image](https://user-images.githubusercontent.com/1573775/113552518-87563780-95f6-11eb-93bb-8a0514efc06c.png)

Below is an export of the configuration of my instance to reproduce the problem:

[api-manager-export.zip](https://github.com/apiman/apiman-docker/files/6257043/api-manager-export.zip)

Just run the container, import the JSON file and try to publish the following API:

![image](https://user-images.githubusercontent.com/1573775/113552676-c2f10180-95f6-11eb-89a0-62ce1c6bad90.png)

You will receive the error.

PS: I have the same behavior when using the ZIP version instead of the docker image.

Thank a lot in advance for your feedback 😃

**Comment by Pabubung** [comment] 2021-04-05 08:32
> results

Thanks, I solved this issue by create new user, in this comment
[https://github.com/apiman/apiman-docker/issues/20#issuecomment-714918483](url)

**Comment by Pabubung** [comment] 2021-04-05 08:34
> This seems that some of the credentials may be wrong.
> Can you go to Gateways -> The Gateway -> and press the "Test" button as described [here](https://apiman.gitbooks.io/apiman-production-guide/content/production-guide/manager/manager.html#_point_the_api_manager_to_the_api_gateway):
> ![image](https://user-images.githubusercontent.com/13332383/112797812-3da4a480-906c-11eb-93b6-bde87d7faf6e.png)
> 
> Then please post the results, also the wildfly log would be helpful for us :)

I solved this problem by creating new user. Like your comment before. Thanks

**Comment by Pabubung** [comment] 2021-04-05 08:36
> @jesseerdmann Please try to create a new user for the gateway and assign the role `apipublisher`.
> Then remove the part before the username in config like so:
> ![image](https://user-images.githubusercontent.com/13332383/96959291-f7b54480-14ff-11eb-8163-a3ccc7e60412.png)

@righettod maybe creating new user can help you

**Comment by righettod** [comment] 2021-04-05 08:43
@Pabubung Thank for the advice 😃 
Where can I assign a role to the new created user ?

**Comment by Pabubung** [comment] 2021-04-05 08:56
> @Pabubung Thank for the advice 😃
> Where can I assign a role to the new created user ?

Sign into your keycloack page (localhost:8080/auth), make sure you're in the apiman realm. Check realm on top left corner.
Go to manage > users. And then you can create user and manage role there

**Comment by righettod** [comment] 2021-04-05 09:04
@Pabubung It has solved the issue, thank a lot !!!!!!!!!!!!!

**Comment by danieleMarenco** [comment] 2021-04-07 09:57
i don't understand where is the default user and password for Keycloak(https://localhost:8443/auth)
i try with admin/admin but is incorrect.

**Comment by righettod** [comment] 2021-04-07 11:05
@danieleMarenco Default creds are `admin / admin123!`
